// main.js - Main p5.js sketch using modules

// Import visualization modules
import FlowerVisualization from './flower.js';
import LorenzVisualization from './lorenz.js';
import LissajousVisualization from './lissajous.js'; // Ensure this import is present

const sketch = (p) => {

    // --- Global State ---
    let currentVizKey = 'about';
    let animateViz = false;
    let animationSpeed = 1.0;
    let visualizations = {}; // Object to hold instances

    // --- DOM References ---
    let vizSelect, animateCheckbox, animSpeedSlider, animSpeedValSpan,
        vizNameSpan, vizFormulaHeaderSpan, titleContainer, animationControlsDiv,
        explanationContainerDiv, specificControlsContainer;

    // --- Content Maps ---
    const vizDisplayNames = { about: "About", flower: "Polar Flower", lorenz: "Lorenz Attractor", lissajous: "Lissajous Curves" };
    const formulas = { about: `Select a visualization...`, flower: `r = <span class="variable">a</span> &sdot; cos(<span class="variable">k</span> &sdot; &theta;)`, lorenz: `dx/dt = &sigma;(y-x), dy/dt = x(&rho;-z)-y, dz/dt = xy-&beta;z <span class='comment'>(2D Projection)</span>`, lissajous: `x = A&sdot;sin(a&sdot;t + &delta;), y = B&sdot;sin(b&sdot;t)` };
    const explanations = {
         about: `Created by Joshua Prull, 2025. Select a visualization from the dropdown.`,
         flower: `<h3>Polar Flower (Rose Curve)</h3><p>This shape is generated by a polar equation where the distance from the center (radius, <code>r</code>) depends on the angle (<code>&theta;</code>). The formula shown is a common way to generate flower-like patterns.</p><p><strong>Parameters:</strong></p><ul><li><span class="variable">a</span> (Amplitude): Controls the overall size of the petals.</li><li><span class="variable">k</span> (Petal Factor): Determines the number and shape of petals. If <span class="variable">k</span> is an integer, the flower has <span class="variable">k</span> petals (if <span class="variable">k</span> is odd) or 2<span class="variable">k</span> petals (if <span class="variable">k</span> is even). If <span class="variable">k</span> is non-integer, more complex patterns emerge.</li></ul>`,
         lorenz: `<h3>Lorenz Attractor</h3><p>This is a famous example of a <strong>dynamic system</strong> exhibiting chaotic behavior, first described by Edward Lorenz in 1963. It arises from a simplified model of atmospheric convection.</p><p>The visualization shows the path (or trajectory) of the system's state over time in a 3D space (represented here by a 2D projection). Even though the governing equations are simple and deterministic (no randomness), the path is highly sensitive to the starting point (the "butterfly effect") and never exactly repeats, tracing out a complex, fractal structure known as a <strong>strange attractor</strong>.</p><p><strong>Why it matters:</strong> The Lorenz system was seminal in the development of <strong>chaos theory</strong>. It demonstrated how complex, unpredictable behavior can emerge from simple, non-linear deterministic rules, impacting fields from weather prediction to biology and economics.</p><p><strong>Parameters:</strong></p><ul><li><span class="variable">&sigma;</span> (Sigma): Related to fluid viscosity and thermal diffusivity (Prandtl number). Affects the shape and contraction rate of the attractor. The classic value is 10.</li><li><span class="variable">&rho;</span> (Rho): Related to the temperature difference driving the convection (Rayleigh number). Primary control for chaotic behavior. Chaos around <span class="variable">&rho;</span> > 24.74. Classic value is 28.</li><li><span class="variable">&beta;</span> (Beta): Related to the physical dimensions. Influences shape and stability. Classic value is 8/3.</li><li><code>Points</code>: Number of steps calculated.</li><li><code>Time Step (dt)</code>: Calculation increment size. Smaller is more accurate but slower.</li></ul>`,
         lissajous: `<h3>Lissajous Curves</h3><p>These curves describe the complex harmonic motion observed when combining two perpendicular oscillations with potentially different frequencies and phases. They were notably demonstrated mechanically by harmonographs.</p><p>The shape traced depends heavily on the ratio of the frequencies (<span class="variable">a</span>/<span class="variable">b</span>) and the phase difference (<span class="variable">&delta;</span>).</p><p>When animated, the curve is traced over time, point by point. The 'Trail Length' controls how many previous points are shown, creating a fading effect.</p><p><strong>Parameters:</strong></p><ul><li><span class="variable">A, B</span>: Amplitudes (width and height) of the X and Y oscillations.</li><li><span class="variable">a, b</span>: Frequencies of the X and Y oscillations. Their ratio determines the pattern complexity.</li><li><span class="variable">&delta;</span> (Delta): Phase difference between oscillations.</li><li><code>Trail Length</code>: Number of past points to display in animation mode.</li><li><code>Point Size</code>: Size of the points drawn in animation mode.</li></ul>`
     };


    p.setup = () => {
        console.log("Main setup running...");
        let canvasContainer = p.select('#canvasContainer'); let controlsContainer = p.select('#controls'); titleContainer = p.select('#vizTitleContainer');
        let availableWidth = p.windowWidth - (controlsContainer ? controlsContainer.width : 300) - 60; let canvasWidth = Math.max(400, availableWidth);
        let availableHeight = p.windowHeight - (titleContainer ? titleContainer.height : 50) - 80; let canvasHeight = Math.min(500, availableHeight);
        let canvas = p.createCanvas(canvasWidth, canvasHeight); canvas.parent('canvasContainer');

        // Get General DOM elements
        vizSelect = p.select('#vizSelect'); animateCheckbox = p.select('#animateCheck'); animSpeedSlider = p.select('#animSpeed'); animSpeedValSpan = p.select('#animSpeedVal');
        vizNameSpan = p.select('#vizName'); vizFormulaHeaderSpan = p.select('#vizFormulaHeader'); animationControlsDiv = p.select('.animation-controls'); explanationContainerDiv = p.select('#explanationContainer');
        specificControlsContainer = p.select('#specificControlsContainer');

        // Instantiate Visualization Modules
        visualizations = {};
        try {
             visualizations['flower'] = new FlowerVisualization(p, p.select('#flowerControls'));
             visualizations['lorenz'] = new LorenzVisualization(p, p.select('#lorenzControls'));
             visualizations['lissajous'] = new LissajousVisualization(p, p.select('#lissajousControls')); // Ensure this is uncommented
             console.log("Visualization modules instantiated:", Object.keys(visualizations));
        } catch (e) { console.error("Error instantiating visualization modules:", e); }

        // Attach Listeners to General Controls
        const addListener = (selector, event, handler) => { const elem = p.select(selector); if (elem) { elem[event](handler); } else { console.warn(`Element not found: ${selector}`); }};
        if (vizSelect) { vizSelect.changed(visualizationChanged); console.log("Dropdown listener attached."); } else { console.error("Could not find #vizSelect!"); }
        addListener('#animateCheck', 'changed', updateGeneralParams);
        addListener('#animSpeed', 'input', updateGeneralParams);
        // Specific listeners are set up within the modules' constructors

        // Initial UI setup
        currentVizKey = vizSelect.value();
        updateGeneralParams(); // Reads initial general controls state
        // *** REMOVED erroneous call to updateParams() here ***
        visualizationChanged(); // Sets up UI based on initial dropdown value

        p.angleMode(p.DEGREES); p.colorMode(p.HSB, 360, 100, 100, 1);
        console.log("Main setup complete.");
    };

    p.draw = () => { // ... (Draw loop identical - calls activeViz.draw()) ...
        p.background(0);
        p.push(); p.fill(0, 100, 100); p.noStroke(); p.ellipse(30, 30, 20, 20); p.pop(); // Sanity check dot

        const activeViz = visualizations[currentVizKey];
        if (activeViz?.draw) {
            const is2D = (currentVizKey === 'flower' || currentVizKey === 'lissajous');
            if (is2D) { p.push(); p.translate(p.width / 2, p.height / 2); }

            activeViz.draw({ animate: animateViz, speed: animationSpeed });

            if (is2D) { p.pop(); }
        } else if (currentVizKey === 'about') {
            p.push(); p.fill(0, 0, 80); p.textAlign(p.CENTER, p.CENTER); p.textSize(18);
            p.text("Select a visualization.", p.width / 2, p.height / 2); p.pop();
        } else {
             console.warn("No active drawing function found for:", currentVizKey);
             p.push(); p.fill(255,0,100); p.textAlign(p.CENTER, p.CENTER); p.textSize(18);
             p.text(`Error: Viz "${currentVizKey}" not found.`, p.width / 2, p.height / 2);
             p.pop();
        }
    };

    // Handles changes to GENERAL controls
    function updateGeneralParams() { // ... (Identical) ...
        if (animateCheckbox) animateViz = animateCheckbox.checked();
        if (animSpeedSlider) animationSpeed = parseFloat(animSpeedSlider.value());
        if (animSpeedValSpan) animSpeedValSpan.html(animationSpeed.toFixed(1));
        const activeViz = visualizations[currentVizKey];
        if ((activeViz?.isAnimatable ? activeViz.isAnimatable() : false)) { p.redraw(); }
    }

    // Handles Dropdown Change
    function visualizationChanged() { // ... (Identical - uses .elt.innerHTML) ...
        if (!vizSelect) return;
        currentVizKey = vizSelect.value();
        console.log("Viz Changed:", currentVizKey);

        const activeViz = visualizations[currentVizKey];
        const displayName = activeViz?.getDisplayName ? activeViz.getDisplayName() : (currentVizKey === 'about' ? "About" : "Unknown");
        const formulaHTML = activeViz?.getFormula ? activeViz.getFormula() : (currentVizKey === 'about' ? "Select a visualization..." : "");

        if (vizNameSpan) vizNameSpan.html(displayName);
        if (vizFormulaHeaderSpan) vizFormulaHeaderSpan.html(formulaHTML);
        if (titleContainer) { titleContainer.style('display', currentVizKey === 'about' ? 'none' : 'block'); }

        const explanationHTML = explanations[currentVizKey] || "";
        if (explanationContainerDiv) { try { explanationContainerDiv.elt.innerHTML = explanationHTML; explanationContainerDiv.style('display', (currentVizKey === 'about' || !explanationHTML) ? 'none' : 'block'); } catch (e) { console.error("Error setting explanation HTML:", e); explanationContainerDiv.elt.innerText = "Error loading explanation."; explanationContainerDiv.style('display', 'block'); } } else { console.warn("Explanation container not found"); }

        const showAnim = activeViz?.isAnimatable ? activeViz.isAnimatable() : false;
        if (animationControlsDiv) { animationControlsDiv.style('display', showAnim ? 'block' : 'none'); }
        if (!showAnim && animateCheckbox?.checked()) { animateCheckbox.checked(false); animateViz = false; }

        for (const key in visualizations) { if(visualizations[key]?.hideControls) visualizations[key].hideControls(); }
        if (activeViz && typeof activeViz.showControls === 'function') {
            activeViz.showControls();
             if(typeof activeViz.activate === 'function') { activeViz.activate(); }
        } else if (currentVizKey !== 'about') { console.warn("No controls found/show method for:", currentVizKey); }

        if (currentVizKey === 'lorenz' && activeViz) { activeViz.needsRecalculation = true; }

        p.redraw();
    }

    // Specific params are updated within the modules via their own listeners now

}; // End sketch function wrapper

// Create the main p5 instance
new p5(sketch);